### ISSUE TITLE
dockerhub image out of date with github dockerfile

### ISSUE THREAD

**Issue by passdan** [ehill-iolani/decona_plus#1]
Hi

Thanks for creating a nice set of extra tools and a docker image around decona. It helped solve issues we were having around installation on a mac and wsl, as well as bonus features.

I realised your dockerhub image is outdated with the dockerfile you have (has the issues with the pandas version and glibC). Building the image locally works, but if you'd be able to update it on dockerhub then that'd be great.

Thanks!

**Comment by ehill-iolani** [comment]
Thanks for reaching out and I'm glad to hear you're finding it useful and for catching the issue, I'll update it hopefully by EOD today.

I also wanted to mention that I have forked the decona/main repo and updated the installation script as well to use mamba instead of conda to drastically reduce the build time. The base decona installation should now take around 5-10 minutes instead of the hours it took previously. 

I'll let you know when I make the push to dockerhub.

**Comment by passdan** [comment]
Thanks for the quick response! Actually I hadn't realised but now you say, the install is so much quicker than when I had done the decona from source before. I'm surprised that mamba makes it quicker by such a large amount!

One issue I've come across however. Tensorflow/Medaka is dependent on numpy 1.19 (according to the original decona .yml and also in your docker), however pandas 1.4.1 requires numpy 1.20.3. I'm checking if reverting pandas to lower will solve, but not sure if it will break your workflows

**Comment by ehill-iolani** [comment]
Thanks for catching that as well! Since switching to mamba, there have been some warnings for compatible packages, like the pandas 1.4.1  and numpy 1.20.3 requirements, but I have not run into issues using them so far. As far as I can tell, this does not currently break the workflow, it just spits warnings.

I also had to pin bcftools at version 1.10 and install using mamba to get medaka to work properly. It will throw the following warning:
```
lib/libtinfow.so.6: no version information available (required by samtools)
```
But again, as far as I can tell, the polishing using medaka still works. I have pushed the updated decona build to https://github.com/ehill-iolani/decona.git and will be pushing the updated decona_plus build with the corresponding docker image to dockerhub shortly.

**Comment by passdan** [comment]
Sorry, I was wrong. pandas is 1.5.2 in the decona environment, although specified 1.4.1 in the dockerfile. I'm not sure why, but I think an earlier call is installing a pandas version, before your later line call.

This was the default in the docker (although note I'm running in singularity)
```
conda list pandas
# packages in environment at /home/passdan/miniconda3/envs/decona:
# Name                    Version                   Build  Channel
pandas                    1.5.2            py38h417a72b_0
```

I did a manual conda install pandas=1.4.1 which corrected.


However I error next on Tensorflow, based on the numpy version. It seems two versions are installed:
```
(decona) Singularity> python
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.20.3'


(decona) Singularity> conda list numpy
# packages in environment at /home/passdan/miniconda3/envs/decona:
#
# Name                    Version                   Build  Channel
numpy                     1.19.0                   pypi_0    pypi
numpy-base                1.20.3           py38h7e635b3_1


(decona) Singularity> pip show numpy
Name: numpy
Version: 1.19.0
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: /home/passdan/miniconda3/envs/decona/lib/python3.8/site-packages
Requires:
Required-by: biopython, Bottleneck, h5py, Keras-Preprocessing, medaka, mkl-fft, mkl-random, nanoget, nanomath, numexpr, ont-fast5-api, opt-einsum, pandas, parasail, scipy, tensorboard, tensorflow
```

**Comment by passdan** [comment]
Sorry, I was wrong. pandas is 1.5.2 in the decona environment, although specified 1.4.1 in the dockerfile. I'm not sure why, but I think there is an earlier call that is installing a pandas version, before your later conda install pandas call.

This was the default in the docker (although note I'm running in singularity)

```
conda list pandas
# packages in environment at /home/passdan/miniconda3/envs/decona:
# Name                    Version                   Build  Channel
pandas                    1.5.2            py38h417a72b_0
```

I did a manual conda install pandas=1.4.1 which corrected and escaped the error

However I do get an error next on Tensorflow, based on the numpy version. It seems that by default it's numpy-base
```
(decona) Singularity> conda list numpy
# packages in environment at /home/passdan/miniconda3/envs/decona:
#
# Name                    Version                   Build  Channel
numpy-base                1.20.3           py38h7e635b3_1
```


However, I'll stop playing and will check out the image that you've built, rather than poking at your work! Thanks for taking a look!

**Comment by ehill-iolani** [comment]
I just pushed the updated build to dockerhub. I think I got rid of the multiple versions of numpy and the compatibility between the pandas seem to working: 
```
(decona) root@1c6a15de1252:/# mamba list pandas
# packages in environment at /root/miniconda3/envs/decona:
#
# Name                    Version                   Build  Channel
pandas                    1.4.1            py38h295c915_1  
(decona) root@1c6a15de1252:/# mamba list numpy 
# packages in environment at /root/miniconda3/envs/decona:
#
# Name                    Version                   Build  Channel
numpy                     1.19.5           py38h7820934_5  
numpy-base                1.19.5           py38hfdd66db_5  
```
I tested it locally and everything seems to be in order. I have not run into conflicts between pandas and numpy in this build so far (at least in the testing that I have done).

Definitely let me know about the issues you encounter with this new build.

Also, if you find a fix for your issues feel free to fork and open a PR, I haven't tried running it with Singularity so if there are Singularity specific bugs you find let me know!

**Comment by passdan** [comment]
Thanks for all this. I'm getting some weird issues still but I think it is a combo of using WSL2 and singularity (Trying to get it running locally for a user that doesn't have access to a server).

I'll test it on a native linux server tomorrow and confirm this, and also see about singularity (never had any issues on conversion before) and let you know how I get on. Thanks!

**Comment by ehill-iolani** [comment]
That sounds good to me, keep me posted.
